package mago.apps.sognorawebsocket.websocket.model

import android.os.Build
import mago.apps.sognorawebsocket.websocket.model.protocol.header.IHeaderInfo

enum class OROT_PROTOCOL(val id: String) {
    PROTOCOL_1("APP_DIALOG_START_REQ"),
    PROTOCOL_2("APP_DIALOG_START_ACK"),
    PROTOCOL_3("APP_UTTERANCE_START_REQ"),
    PROTOCOL_4("APP_UTTERANCE_START_ACK"),
    PROTOCOL_5("AUDIO STREAM"), // not used
    PROTOCOL_6("EPD"),  // not used
    PROTOCOL_7("STT_REQ"), // not used
    PROTOCOL_8("STT_RES"), // not used
    PROTOCOL_9("STT_REQ"), // not used
    PROTOCOL_10("STT_RES"), // not used
    PROTOCOL_11("STT_RESPONSE_DELIVERY"),
    PROTOCOL_12("AI_NEXT_QUESTION_DELIVERY"),
    PROTOCOL_13("APP_UTTERANCE_END_REQ"),
    PROTOCOL_14("APP_UTTERANCE_END_ACK"),
    PROTOCOL_15("DEVICE_MEASUREMENT_ENTRY_REQ"),
    PROTOCOL_16("DEVICE_MEASUREMENT_ENTRY_ACK"),
    PROTOCOL_17("DEVICE_MEASUREMENT_DELIVERY"),
    PROTOCOL_18("APP_MEASUREMENT_ENTRY_REQ"),
    PROTOCOL_19("APP_MEASUREMENT_ENTRY_ACK"),
    PROTOCOL_20("APP_DIALOG_END_REQ"),
    PROTOCOL_21("APP_DIALOG_END_ACK"),
    PROTOCOL_99("STT_FALLBACK_DELIVERY")
}






